/* FFP Taxonomy - v1 (2026-05-31)
   v1: single source of truth for cross-platform reference lists, extracted VERBATIM from
       the member dashboard (CITIES_DB, ACTIVITIES_DB) + shared fitness levels + nationalities.
       Loaded before dashboards; forms/admin read window.FFP_TAX instead of inline copies.
*/
(function(){
  'use strict';
  window.FFP_TAX = {
    cities: {

      'Argentina': ['Bariloche','Buenos Aires','Cordoba','El Calafate','Iguazu','Mendoza','Salta','Ushuaia'],
      'Australia': ['Adelaide','Brisbane','Byron Bay','Cairns','Canberra','Darwin','Gold Coast','Hobart','Melbourne','Newcastle','Perth','Sunshine Coast','Sydney','Wollongong'],
      'Austria': ['Bregenz','Graz','Hallstatt','Innsbruck','Kitzbuhel','Klagenfurt','Linz','Salzburg','Vienna'],
      'Bahrain': ['Manama','Muharraq','Riffa'],
      'Belgium': ['Antwerp','Bruges','Brussels','Ghent','Leuven','Liege','Mechelen','Namur'],
      'Brazil': ['Brasilia','Buzios','Florianopolis','Fortaleza','Iguazu Falls','Manaus','Recife','Rio de Janeiro','Salvador','Sao Paulo'],
      'Canada': ['Banff','Calgary','Edmonton','Halifax','Mont-Tremblant','Montreal','Niagara Falls','Ottawa','Quebec City','Toronto','Vancouver','Victoria','Whistler','Winnipeg'],
      'Chile': ['Atacama','Easter Island','Patagonia','Pucon','Punta Arenas','Santiago','Valparaiso'],
      'China': ['Beijing','Chengdu','Chongqing','Guangzhou','Hangzhou','Hong Kong','Lhasa','Macau','Sanya','Shanghai','Shenzhen','Suzhou','Xian'],
      'Costa Rica': ['La Fortuna','Manuel Antonio','Monteverde','Puerto Viejo','San Jose','Tamarindo'],
      'Czech Republic': ['Brno','Cesky Krumlov','Karlovy Vary','Liberec','Olomouc','Ostrava','Plzen','Prague'],
      'Denmark': ['Aalborg','Aarhus','Copenhagen','Esbjerg','Helsingor','Odense','Roskilde'],
      'Egypt': ['Alexandria','Aswan','Cairo','Dahab','Hurghada','Luxor','Marsa Alam','Sharm El Sheikh'],
      'Finland': ['Espoo','Helsinki','Lapland','Oulu','Rovaniemi','Tampere','Turku','Vantaa'],
      'France': ['Aix-en-Provence','Avignon','Biarritz','Bordeaux','Cannes','Chamonix','Lille','Lyon','Marseille','Montpellier','Nantes','Nice','Paris','Saint-Tropez','Strasbourg','Toulouse'],
      'Germany': ['Baden-Baden','Berlin','Bremen','Cologne','Dresden','Dusseldorf','Frankfurt','Hamburg','Hannover','Heidelberg','Leipzig','Munich','Nuremberg','Stuttgart'],
      'Greece': ['Athens','Corfu','Crete','Kos','Mykonos','Naxos','Paros','Patras','Rhodes','Santorini','Skiathos','Thessaloniki','Zakynthos'],
      'Hungary': ['Budapest','Debrecen','Eger','Gyor','Miskolc','Pecs','Szeged'],
      'Iceland': ['Akureyri','Hofn','Husavik','Keflavik','Reykjavik','Selfoss','Vik'],
      'India': ['Agra','Bangalore','Chennai','Darjeeling','Goa','Hyderabad','Jaipur','Kerala','Kolkata','Mumbai','New Delhi','Pune','Rishikesh','Udaipur','Varanasi'],
      'Indonesia': ['Bali','Bandung','Gili Islands','Jakarta','Komodo','Lombok','Seminyak','Surabaya','Ubud','Yogyakarta'],
      'Ireland': ['Belfast','Cork','Dublin','Galway','Kilkenny','Killarney','Limerick','Waterford'],
      'Israel': ['Eilat','Haifa','Jerusalem','Nazareth','Tel Aviv','Tiberias'],
      'Italy': ['Amalfi','Bologna','Capri','Cinque Terre','Florence','Genoa','Lake Como','Milan','Naples','Palermo','Pisa','Positano','Rome','Sardinia','Sicily','Turin','Venice','Verona'],
      'Japan': ['Fukuoka','Hakone','Hiroshima','Kanazawa','Kobe','Kyoto','Nagoya','Nara','Nikko','Niseko','Okinawa','Osaka','Sapporo','Sendai','Takayama','Tokyo','Yokohama'],
      'Jordan': ['Amman','Aqaba','Dead Sea','Jerash','Petra','Wadi Rum'],
      'Kenya': ['Diani Beach','Kisumu','Lamu','Maasai Mara','Mombasa','Nairobi','Nakuru'],
      'Kuwait': ['Hawalli','Kuwait City','Salmiya'],
      'Lebanon': ['Baalbek','Beirut','Byblos','Sidon','Tripoli'],
      'Malaysia': ['Borneo','Ipoh','Johor Bahru','Kota Kinabalu','Kuala Lumpur','Kuching','Langkawi','Malacca','Penang'],
      'Maldives': ['Hulhumale','Maafushi','Male'],
      'Mexico': ['Cabo San Lucas','Cancun','Cozumel','Guadalajara','Isla Mujeres','Merida','Mexico City','Oaxaca','Playa del Carmen','Puerto Vallarta','Tulum'],
      'Morocco': ['Agadir','Casablanca','Chefchaouen','Essaouira','Fez','Marrakech','Meknes','Rabat','Tangier'],
      'Netherlands': ['Amsterdam','Delft','Eindhoven','Groningen','Haarlem','Leiden','Maastricht','Rotterdam','The Hague','Utrecht'],
      'New Zealand': ['Auckland','Christchurch','Dunedin','Hamilton','Napier','Nelson','Queenstown','Rotorua','Tauranga','Wellington'],
      'Norway': ['Alesund','Bergen','Geiranger','Lofoten','Oslo','Stavanger','Tromso','Trondheim'],
      'Oman': ['Khasab','Muscat','Nizwa','Salalah','Sur'],
      'Philippines': ['Boracay','Bohol','Cebu','Coron','Davao','El Nido','Manila','Palawan','Siargao'],
      'Poland': ['Gdansk','Krakow','Lodz','Lublin','Poznan','Warsaw','Wroclaw','Zakopane'],
      'Portugal': ['Albufeira','Azores','Braga','Cascais','Coimbra','Faro','Funchal','Lagos','Lisbon','Madeira','Porto','Sintra'],
      'Qatar': ['Al Khor','Al Wakrah','Doha','Lusail'],
      'Russia': ['Kazan','Moscow','Novosibirsk','Saint Petersburg','Sochi','Vladivostok','Yekaterinburg'],
      'Saudi Arabia': ['AlUla','Dammam','Jeddah','Khobar','Mecca','Medina','NEOM','Riyadh'],
      'Singapore': ['Singapore'],
      'South Africa': ['Cape Town','Durban','Hermanus','Johannesburg','Knysna','Plettenberg Bay','Port Elizabeth','Pretoria','Stellenbosch'],
      'South Korea': ['Busan','Daegu','Daejeon','Gwangju','Gyeongju','Incheon','Jeju','Seoul','Suwon'],
      'Spain': ['Barcelona','Bilbao','Cordoba','Granada','Gran Canaria','Ibiza','Madrid','Malaga','Mallorca','Marbella','Salamanca','San Sebastian','Seville','Tenerife','Valencia'],
      'Sri Lanka': ['Anuradhapura','Colombo','Ella','Galle','Kandy','Mirissa','Negombo','Nuwara Eliya'],
      'Sweden': ['Gothenburg','Kiruna','Lapland','Lund','Malmo','Stockholm','Uppsala','Vasteras'],
      'Switzerland': ['Basel','Bern','Davos','Geneva','Interlaken','Lausanne','Lucerne','Lugano','Montreux','St. Moritz','Zermatt','Zurich'],
      'Taiwan': ['Hualien','Kaohsiung','Taichung','Tainan','Taipei','Taroko'],
      'Tanzania': ['Arusha','Dar es Salaam','Kilimanjaro','Serengeti','Stone Town','Zanzibar'],
      'Thailand': ['Bangkok','Chiang Mai','Chiang Rai','Hua Hin','Koh Phi Phi','Koh Samui','Koh Tao','Krabi','Pattaya','Phuket'],
      'Turkey': ['Ankara','Antalya','Bodrum','Cappadocia','Fethiye','Istanbul','Izmir','Marmaris','Pamukkale'],
      'United Arab Emirates': ['Abu Dhabi','Ajman','Al Ain','Dubai','Fujairah','Ras Al Khaimah','Sharjah','Umm Al Quwain'],
      'United Kingdom': ['Aberdeen','Bath','Belfast','Birmingham','Brighton','Bristol','Cambridge','Cardiff','Edinburgh','Glasgow','Leeds','Liverpool','London','Manchester','Newcastle','Oxford','Sheffield','York'],
      'United States': ['Aspen','Atlanta','Austin','Boston','Chicago','Dallas','Denver','Honolulu','Houston','Las Vegas','Los Angeles','Miami','Nashville','New Orleans','New York','Park City','Philadelphia','Phoenix','Portland','San Antonio','San Diego','San Francisco','Seattle','Washington DC'],
      'Vietnam': ['Da Nang','Dalat','Halong Bay','Hanoi','Ho Chi Minh City','Hoi An','Hue','Nha Trang','Phu Quoc','Sapa']
    },
    activities: [
      {n:'Walk 2km',c:'Running & walking'},{n:'Walk 5km',c:'Running & walking'},{n:'Walk 10km',c:'Running & walking'},
      {n:'Run 2km',c:'Running & walking'},{n:'Run 5km',c:'Running & walking'},{n:'Run 10km',c:'Running & walking'},
      {n:'Half marathon',c:'Running & walking'},{n:'Marathon',c:'Running & walking'},{n:'Trail run',c:'Running & walking'},
      {n:'Road cycling',c:'Cycling'},{n:'Mountain biking',c:'Cycling'},{n:'Indoor cycling',c:'Cycling'},{n:'Track cycling',c:'Cycling'},
      {n:'Pool swim',c:'Swimming'},{n:'Open water swim',c:'Swimming'},{n:'Lap swim',c:'Swimming'},
      {n:'Surfing',c:'Watersports'},{n:'Kitesurfing',c:'Watersports'},{n:'Stand-up paddleboard',c:'Watersports'},{n:'Sailing',c:'Watersports'},{n:'Kayaking',c:'Watersports'},{n:'Scuba diving',c:'Watersports'},
      {n:'Tennis',c:'Racquet sports'},{n:'Padel',c:'Racquet sports'},{n:'Pickleball',c:'Racquet sports'},{n:'Squash',c:'Racquet sports'},{n:'Badminton',c:'Racquet sports'},
      {n:'Football (soccer)',c:'Team sports'},{n:'Futsal',c:'Team sports'},{n:'American football',c:'Team sports'},{n:'Australian rules football',c:'Team sports'},
      {n:'Basketball',c:'Team sports'},{n:'Baseball',c:'Team sports'},{n:'Cricket',c:'Team sports'},
      {n:'Rugby union',c:'Team sports'},{n:'Rugby league',c:'Team sports'},{n:'Rugby sevens',c:'Team sports'},{n:'Touch rugby',c:'Team sports'},
      {n:'Ice hockey',c:'Team sports'},{n:'Field hockey',c:'Team sports'},{n:'Lacrosse',c:'Team sports'},
      {n:'Volleyball',c:'Team sports'},{n:'Beach volleyball',c:'Team sports'},{n:'Water polo',c:'Team sports'},
      {n:'Netball',c:'Team sports'},{n:'Handball',c:'Team sports'},{n:'Kabaddi',c:'Team sports'},{n:'Dodgeball',c:'Team sports'},
      {n:'Ultimate frisbee',c:'Team sports'},{n:'Curling',c:'Team sports'},
      {n:'Boxing',c:'Combat sports'},{n:'Kickboxing',c:'Combat sports'},{n:'Muay Thai',c:'Combat sports'},
      {n:'Brazilian Jiu-Jitsu',c:'Combat sports'},{n:'MMA',c:'Combat sports'},{n:'Judo',c:'Combat sports'},
      {n:'Karate',c:'Combat sports'},{n:'Taekwondo',c:'Combat sports'},{n:'Wrestling',c:'Combat sports'},{n:'Fencing',c:'Combat sports'},
      {n:'Strength training',c:'Strength & fitness'},{n:'Powerlifting',c:'Strength & fitness'},{n:'Olympic lifting',c:'Strength & fitness'},
      {n:'CrossFit',c:'Strength & fitness'},{n:'HIIT',c:'Strength & fitness'},{n:'F45',c:'Strength & fitness'},
      {n:'Functional training',c:'Strength & fitness'},{n:'Calisthenics',c:'Strength & fitness'},
      {n:'Vinyasa yoga',c:'Mind-body'},{n:'Hot yoga',c:'Mind-body'},{n:'Yin yoga',c:'Mind-body'},
      {n:'Pilates mat',c:'Mind-body'},{n:'Pilates reformer',c:'Mind-body'},{n:'Barre',c:'Mind-body'},
      {n:'Meditation',c:'Mind-body'},{n:'Breathwork',c:'Mind-body'},{n:'Tai Chi',c:'Mind-body'},
      {n:'Cryotherapy',c:'Recovery & wellness'},{n:'Ice bath',c:'Recovery & wellness'},{n:'Sauna',c:'Recovery & wellness'},
      {n:'Infrared sauna',c:'Recovery & wellness'},{n:'Sports massage',c:'Recovery & wellness'},
      {n:'Hiking',c:'Outdoor & adventure'},{n:'Mountain hike',c:'Outdoor & adventure'},{n:'Indoor climbing',c:'Outdoor & adventure'},
      {n:'Outdoor climbing',c:'Outdoor & adventure'},{n:'Bouldering',c:'Outdoor & adventure'},
      {n:'Skiing',c:'Snow sports'},{n:'Snowboarding',c:'Snow sports'},{n:'Cross-country skiing',c:'Snow sports'},
      {n:'Golf round',c:'Golf'},{n:'Driving range',c:'Golf'},
      {n:'Horse riding',c:'Equestrian'},{n:'Polo',c:'Equestrian'},
      {n:'Skydiving',c:'Air & extreme'},{n:'Paragliding',c:'Air & extreme'},{n:'Bungee jump',c:'Air & extreme'},
      {n:'Triathlon',c:'Multi-sport'},{n:'Ironman',c:'Multi-sport'},{n:'Hyrox',c:'Multi-sport'},{n:'Spartan',c:'Multi-sport'}
    ],
    fitnessLevels: ['Beginner','Intermediate','Advanced','Elite','Professional'],
    nationalities: [
      'Argentinian','Australian','Austrian','Belgian','Brazilian','British','Bulgarian',
      'Canadian','Chilean','Chinese','Colombian','Croatian','Czech','Danish','Dutch',
      'Egyptian','Emirati','Filipino','Finnish','French','German','Greek','Hungarian',
      'Indian','Indonesian','Irish','Israeli','Italian','Japanese','Jordanian','Kenyan',
      'Kuwaiti','Lebanese','Malaysian','Mexican','Moroccan','New Zealander','Nigerian',
      'Norwegian','Omani','Pakistani','Peruvian','Polish','Portuguese','Qatari','Romanian',
      'Russian','Saudi Arabian','Singaporean','South African','South Korean','Spanish',
      'Sri Lankan','Swedish','Swiss','Thai','Turkish','Ukrainian','American','Vietnamese'
    ]
  };
  // convenience: flat sorted city list across all countries
  window.FFP_TAX.allCities = function(){ var o=[]; var c=window.FFP_TAX.cities||{}; Object.keys(c).forEach(function(k){ (c[k]||[]).forEach(function(x){o.push(x);}); }); return o.sort(); };
})();
